// <auto-generated />
using System;
using AwoxController.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AwoxController.Data.Migrations
{
    [DbContext(typeof(AwoxDbContext))]
    [Migration("20260608151604_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AwoxController.Core.Models.LampDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Mac")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("varchar(17)");

                    b.Property<int>("MeshId")
                        .HasColumnType("int");

                    b.Property<int?>("MeshNetworkId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Protocol")
                        .HasColumnType("int");

                    b.Property<string>("Room")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Mac")
                        .IsUnique();

                    b.HasIndex("MeshNetworkId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("lamps", (string)null);
                });

            modelBuilder.Entity("AwoxController.Core.Models.MeshNetwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MeshKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("MeshName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("MeshPassword")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Service")
                        .IsUnique();

                    b.ToTable("meshes", (string)null);
                });

            modelBuilder.Entity("AwoxController.Core.Models.LampDevice", b =>
                {
                    b.HasOne("AwoxController.Core.Models.MeshNetwork", "Mesh")
                        .WithMany("Lamps")
                        .HasForeignKey("MeshNetworkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Mesh");
                });

            modelBuilder.Entity("AwoxController.Core.Models.MeshNetwork", b =>
                {
                    b.Navigation("Lamps");
                });
#pragma warning restore 612, 618
        }
    }
}
